# Генерация случайного вопроса
GET http://localhost:8080/question/random


# Проверка ответа на данный вопрос
POST http://localhost:8080/question/check
json:
{
  "questionId": 2,
  "answer": "центнер"
}


# Генерация игры по заданным параметрам: количество вопросов, min сложность и max сложность
POST http://localhost:8080/game
json:
{
    "count": 5,
    "minDifficulty": 10,
    "maxDifficulty": 210
}


# Просмотр вопроса по заданному номеру вопроса в игре, например 1
GET http://localhost:8080/game/game_id/1


# Проверка ответа на данный вопрос (первый)
POST http://localhost:8080/game/game_id/1/check
json:
{
  "answer": 1024
}


# Завершени игры и просмотр всех правильных и неправильных ответов
POST http://localhost:8080/game/game_id/finish